#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: Mod from P3TERX
# For NanoPi R2S slim
#=================================================

name: Build R2S OpenWrt Slim

on:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - '.github/workflows/openwrt-r2s-slim.yml'
      - 'seed/slim.seed'
      - 'r2s_step/06_mod_slim.sh'
  schedule:
    - cron: 30 20 * * *
  watch:
    types: started

env:
  REPO_BRANCH: master
  CONFIG_FILE: seed/slim.seed
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
    build:
      runs-on: ubuntu-18.04
      if: github.event.repository.owner.id == github.event.sender.id

      steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          /bin/bash r2s_step/00_init_env.sh

      - name: Install friendlywrt source
        run: |
          /bin/bash r2s_step/01_friendlywrt.sh

      - name: rebase Lean opwrt
        run: |
          /bin/bash r2s_step/02_rebase2lean.sh

      - name: Update kernel-rockchip
        run: |
          cd friendlywrt-rk3328/kernel
          git remote add upstream https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git && git fetch upstream
          git rebase upstream/linux-5.4.y

      - name: Patch 5.4 Kernel
        run: |
          /bin/bash r2s_step/03_kernel_patch.sh

      - name: Enable Kernel feature
        run: |
          /bin/bash r2s_step/04_fullcone_1.5g.sh
 
      - name: Enable cpu autocore
        run: |
          cd friendlywrt-rk3328/friendlywrt/
          git apply ../../patches/001-cpu-enable_autocore.patch
          
      - name: MOD the OpenWrt
        run: |
          /bin/bash r2s_step/06_mod_slim.sh

      - name: Load config
        run: |
          /bin/bash r2s_step/09_load_config.sh
      
      - name: Build OpenWrt
        run: |
          cd friendlywrt-rk3328
          ./build.sh nanopi_r2s.mk
      
      - name: Fix Rootfs Owner and Group
        run: |
          /bin/bash r2s_step/10_fix_rootfs.sh

      - name: Organize files
        id: organize
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv friendlywrt-rk3328/out/*img* ./artifact/
          cd ./artifact/
          gzip *.img
          zip R2S-slim-$(date +%Y-%m-%d).zip *.img.gz
          rm *.img.gz
          echo "::set-env name=FIRMWARE::$PWD"
          echo "::set-output name=status::success"
          echo "::set-env name=DATE::$(date "+%Y-%m-%d %H:%M:%S")"
          release_tag="NanoPi-R2S-${{ env.DATE }}-slim"
          echo "##[set-output name=release_tag;]$release_tag"
          cd ../friendlywrt-rk3328/friendlywrt
          cp .config ../../artifact/config-slim-full
          ./scripts/diffconfig.sh > ../../artifact/config-slim.seed

      - name: Upload artifact
        uses: actions/upload-artifact@master
        if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
        with:
          name: OpenWrt_R2S_slim_firmware
          path: ${{ env.FIRMWARE }}

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1.6.1
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          name: 最新编译时间:${{ env.DATE }}
          allowUpdates: true
          tag: R2S
          commit: master
          replacesArtifacts: true
          token: ${{ secrets.RELEASES_TOKEN }}
          body: |
            最新编译版本: ${{ steps.organize.outputs.release_tag }}
          artifacts: ${{ env.FIRMWARE }}/*.zip,${{ env.FIRMWARE }}/config*