#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: Mod from P3TERX
# For NanoPi R2S org
#=================================================

name: Build R2S OpenWrt Origin

on:
#  release:
#    types: published
  push:
    branches:
      - master
    paths:
      - '.github/workflows/r2s-origin.yml'
      - 'test/06_mod_test.sh'
      - 'seed/test.seed'
  schedule:
    - cron: 35 21 * * *
  watch:
    types: started

env:
  CONFIG_FILE: seed/test.seed
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  RK3328_DIR: rk3328
  TZ: Asia/Shanghai

jobs:
    build:
      runs-on: ubuntu-18.04
      if: github.event.repository.owner.id == github.event.sender.id

      steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          /bin/bash test/00_init_env.sh

      - name: Install fanck0605 source
        run: |
          /bin/bash test/01_fanck0605.sh

      - name: Patch 5.4 Kernel
        run: |
          /bin/bash test/03_kernel_patch.sh

      - name: Enable Kernel feature
        run: |
          /bin/bash test/04_fullcone_1.5g.sh
 
      - name: Unlock some OpenWrt feeds
        run: |
          cd $RK3328_DIR/friendlywrt

      - name: MOD the OpenWrt
        run: |
          /bin/bash test/06_mod_test.sh

      - name: Load config
        run: |
          /bin/bash test/09_load_config_test.sh
      
      - name: Build OpenWrt
        run: |
          cd $RK3328_DIR
          ./build.sh nanopi_r2s.mk
      
      - name: Fix Rootfs Owner and Group
        run: |
          sudo df -lh
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          sudo losetup -P $lodev $RK3328_DIR/out/*.img
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount ${lodev}p1 /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d $lodev

      - name: Organize files
        id: organize
        run: |
          . test/11_organize_test.sh
        
      - name: Upload artifact
        uses: actions/upload-artifact@master
        if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
        with:
          name: OpenWrt_R2S_origin_firmware
          path: ${{ env.FIRMWARE }}

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1.6.1
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          name: R2S最新编译时间:${{ env.DATE }}
          allowUpdates: true
          tag: R2S
          commit: master
          replacesArtifacts: true
          token: ${{ secrets.RELEASES_TOKEN }}
          body: |
            最新编译版本: ${{ steps.organize.outputs.release_tag }}
            源码最近更新时间: ${{ env.VersionDate }}
          artifacts: ${{ env.FIRMWARE }}/*.zip,${{ env.FIRMWARE }}/config*
